version: '3'
services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: drkiq_development
    ports:
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:3.0.5
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data
  
  drkiq:
    build: .
    volumes:
      - ./drkiq_app:/drkiq
    ports:
      - '8000:8000'
    environment:
      SECRET_TOKEN: 33bcbea703379cedd7055ab152741922b2765dc4d68540b935b9be8161fd379a143edebf8ed8121326fd2950e05c561d8a6be72347b2d9e99ece7327e0b7cc2c
      WORKER_PROCESSES: 1
      LISTEN_ON: 0.0.0.0:8000
      DATABASE_URL: postgresql://drkiq:123456@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
      CACHE_URL: redis://redis:6379/0
      JOB_WORKER_URL: redis://redis:6379/0
#    env_file:
#      - ./drkiq_app/.drkiq.env
  
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ./drkiq_app:/drkiq
    environment:
      SECRET_TOKEN: 33bcbea703379cedd7055ab152741922b2765dc4d68540b935b9be8161fd379a143edebf8ed8121326fd2950e05c561d8a6be72347b2d9e99ece7327e0b7cc2c
      WORKER_PROCESSES: 1
      LISTEN_ON: 0.0.0.0:8000
      DATABASE_URL: postgresql://drkiq:123456@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
      CACHE_URL: redis://redis:6379/0
      JOB_WORKER_URL: redis://redis:6379/0
#    env_file:
#      - ./drkiq_app/.drkiq.env
volumes:
  drkiq-postgres:
  drkiq-redis:
